#x=open("new task.txt","x")
#x.close()
# y=open("new task.txt","w")
# print(y.write("Hai,I am Malin"))
# y.close()
# z=open("new task.txt","r")
# print(z.read())
# z.close()
#x1=open("b.txt","x")                                               #Created new file
#x1.close()
#x2=open("a.txt","x")
#x2.close()
y1=open("new task.txt","r")                                   #Read the first file
m=y1.read() 
print(m)
y1.close()
#-y2=open("b.txt","w")                                               
#y2.write(m)                                                        
#y2.close()
y2=open("a.txt","w")                                               
y2.write(m)                                                        
y2.close()
#y3=open("b.txt","r")
#print(y3.read())
y3=open("a.txt","r")
print(y3.read())